### ISSUE TITLE
New WOFF2 file seems to trigger an error in Firefox v47

### ISSUE THREAD

**Issue by kurtextrem** [filamentgroup/woff2-feature-test#18]
http://prntscr.com/c4er2l
ref #15

**Comment by zachleat** [comment]
cc @RoelN

**Comment by RoelN** [comment]
Ah, seems like a bug in Nanofont which I used: https://github.com/bramstein/nanofont/issues/5

I took a stripped-down font from [ChromaCheck](https://github.com/RoelN/ChromaCheck) minus the color glyphs. A few bytes more, but it works now. See https://github.com/filamentgroup/woff2-feature-test/pull/19

**Comment by szarouski** [comment]
I guess this ticket can be closed? :)

**Comment by maninak** [comment]
Still getting this in Firefox 55.0.2 (64bit) on Linux.

For what it's worth, because the exception is caught loading of woff2 files continues properly. So no false negative produced although having errors in the console is undesirable.

Will need to investigate if this also produces false negatives on older browsers.
